name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('./src/.env') || copy('./src/.env.example', './src/.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ./src

      - name: Generate key
        run: php src/artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 src/storage src/bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p src/database
          touch src/database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: src/database/database.sqlite
        run: cd ./src && ./vendor/bin/phpunit

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 54.80.241.149
          port: 22
          username: convertedin
          key: ${{ secrets.PRIVATE_KEY }}
          script: "cd www && git pull origin main"